kind: pipeline
name: default

steps:
  - name: build
    image: gradle:6.5.1-jdk11
    commands:
      - gradle build

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token